## Problem
(Describe what you want)

## Constraints
- Language / framework:
- Must not break:
- Performance / security constraints:
- Time/complexity constraints:

## Claude Plan Request
@claude Please produce an executable plan using this exact format:

1) Goal
2) Non-goals
3) Assumptions / Open questions
4) Plan (numbered steps; each step <= 1 PR commit scope)
5) Acceptance Criteria (checklist)
6) Test Plan (commands to run)
7) Risk & Rollback


# 为什么有效：它强制把“验收标准”和“测试命令”写出来，Codex 更容易自检；Claude Review 也更可对照。 ￼